# Terminology
# LR_img: Low Resolution Image
# HR_img: High Resolution Image
# SR_img: Super Resolution Image <- model output

# Data Location
# Celeb-A dataset  <- img shape: (218, 178, 3)
dataset_dir: "E:/Data_Hub/CelebA_dataset/img_align_celeba"
dataset_save_path: "./tf_data_save/saved_data"

# img data related

# High resolution image
H_img_height: 256
H_img_width: 256

# Low resolution image
L_img_height: 64        # H_img_height // 4
L_img_width: 64         # H_img_height // 4


batch_size: 16
vgg_loss_model: "54"    # 22 or 54

epochs: 100
log_save_path: './model_train/ckpt'
max_to_keep: 5
keep_checkpoint_envery_n_hours: 3

# Tensorboard
log_dir: './logs/